{
 "title": "Nomad-Consul-Cluster",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(nomad_client_uptime{datacenter=~\"$datacenter\"}, host)"
    }
   },
   {
    "name": "datacenter",
    "label": "DC",
    "query": {
     "query": "label_values(nomad_client_uptime, datacenter)"
    }
   },
   {
    "name": "instanace",
    "label": "Instance",
    "query": {
     "query": "consul_raft_state_leader{job=\"consul\"}"
    }
   },
   { "name": "prometheus", "query": { "query": "label_values( prometheus)" } }
  ]
 },
 "panels": [
  { "title": "Nomad", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running Nomad Jobs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nomad_nomad_job_status_running" }
   ]
  },
  {
   "title": "Nomad Failed Jobs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nomad_nomad_job_summary_failed)"
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(nomad_client_uptime)" }
   ]
  },
  {
   "title": "Nomad CPU Total Ticks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "repeat": "host",
   "yaxes": [
    { "format": "timeticks" }
   ],
   "targets": [
    {
     "expr": "avg(nomad_client_allocs_cpu_total_ticks{host=~\"$host\"}) by(exported_job, task)",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "Nomad Memory Cache",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "repeat": "host",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(nomad_client_allocs_memory_cache{host=~\"$host\"}) by(exported_job, task)",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "Nomad CPU Usage Percent",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 9 },
   "repeat": "host",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(nomad_client_allocs_cpu_total_percent{host=~\"$host\"}) by(exported_job, task)",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "Nomad Disk Usage ($host)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "repeat": "host",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max(nomad_client_host_disk_size{datacenter=~\"$datacenter\", host=~\"$host\"}) by (disk)",
     "legendFormat": "Total - {{disk}}"
    },
    {
     "expr": "avg(nomad_client_host_disk_available{datacenter=~\"$datacenter\", host=~\"$host\"}) by (disk)",
     "legendFormat": "Available - {{disk}}"
    }
   ]
  },
  { "title": "Consul", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Consul Number of Unique Services ",
   "type": "stat",
   "description": "This measures the current number of unique services registered with Consul, based on service name.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(consul_consul_state_services)"
    }
   ]
  },
  {
   "title": "Consul Leader",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "consul_raft_state_leader{job=\"consul\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Raft Apply Rate [ /minute ]",
   "type": "graph",
   "description": "This counts the number of Raft transactions occurring over the interval, which is a general indicator of the write load on the Consul servers.\t",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "rate(consul_raft_apply[1m])", "legendFormat": "{{ job}} " }
   ]
  },
  {
   "title": "Consul Raft Commit Time",
   "type": "graph",
   "description": "This measures the time it takes to commit a new entry to the Raft log on the leader.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(consul_raft_commitTime) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Consul Autopilot Health",
   "type": "graph",
   "description": "This tracks the overall health of the local server cluster. If all servers are considered healthy by Autopilot, this will be set to 1. If any are unhealthy, this will be 0",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "consul_autopilot_healthy" }
   ]
  }
 ]
}